### ISSUE TITLE
TPV to access resource and job information

### ISSUE THREAD

**Issue by abdulrahmanazab** [usegalaxy-eu/tpv-metascheduler-api#2]
There is an app through which TPV can access Galaxy information. Such information collection will be useful for TPV to have access to non-(manual + Static) "additional" information about: jobs, destinations, and object stores. How to consume this app?

We want an implementation that goes into Galaxy to get e.g. aggregated job information. Example: running jobs on destination D accessing Data on Object store O, we want to collect the BW information so that it can be used for future matchmaking decisions involving O and D

**Comment by pauldg** [comment]
Partly addressed by https://github.com/usegalaxy-eu/tpv-metascheduler-api/pull/5
