### ISSUE TITLE
Additional attributes for an API request

### ISSUE THREAD

**Issue by abdulrahmanazab** [usegalaxy-eu/tpv-metascheduler-api#3]
Would be great to add these attributes for the matchmaking to be implemented (example values):

"selected_objectstore": "object_store_italy_S3_01",
   "cores" : 8,
   "mem" : 20,
   "Platform" : "Debian",
   "prefered dest" : "condor-tpv"

**Comment by pauldg** [comment]
@abdulrahmanazab Can you remind me, are these job related attributes?

**Comment by abdulrahmanazab** [comment]
@pauldg  Yepp, as mentioned in the chat. In order to do the actual matchmaking, we need to add job attributes (requirements) to match them against the destination attributes (resource specifications), in addition to the consideration of locality, i.e. where are the input datasets stored (and if relevant, where the should the results be stored)

**Comment by pauldg** [comment]
Discussed during the meetings, tpv handles the matchmaking based on job requirements.
